"""Initial migration.

Revision ID: 7fb4448a3dad
Revises: 
Create Date: 2025-12-05 23:20:18.280756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fb4448a3dad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'TEACHER', name='userrole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('attachment', sa.JSON(), nullable=True),
    sa.Column('conversation_id', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_attempts',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('module_id', sa.String(length=80), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['module_stats.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('options', sa.String(), nullable=False),
    sa.Column('correct_answer', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=120), nullable=False),
    sa.Column('module_id', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['module_stats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transcript_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'TEACHER', name='userrole'), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('live_session_id', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['live_session_id'], ['live_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transcript_items')
    op.drop_table('quiz_questions')
    op.drop_table('quiz_attempts')
    op.drop_table('messages')
    # ### end Alembic commands ###
